### ISSUE TITLE
Media component only works when passing children prop rather than render prop

### ISSUE THREAD

**Issue by morsdyce** [jaredpalmer/react-fns#63]
The following does not work:

```js
import { Media } from 'react-fns'

const Example = () =>
  <Media
    query="(min-width: 1000px)"
    render={(match) =>
     <div>
        {match ? 'mobile' : 'desktop'}
     </div>
    }
  />

export default Example
```

but this does:
```js
import { Media } from 'react-fns'

const Example = () =>
  <Media
    query="(min-width: 1000px)"
    children={(match) =>
     <div>
        {match ? 'mobile' : 'desktop'}
     </div>
    }
  />

export default Example
```

**Comment by macklinu** [comment]
I was curious about this and could reproduce it on [CodeSandbox](https://codesandbox.io/s/9lpxwpqq1w):

![image](https://user-images.githubusercontent.com/2344137/35188916-bcaf671e-fe0d-11e7-8116-46ae5c61176d.png)

**Comment by Gabri3l** [comment]
From my understanding this is actually expected behavior, directly form the `react-media` docs we have:

> or the common case of "only render something when the media query matches", you can use a render prop that is only called if the query matches.

In the example from this issue, we are matching the `else` clause of the ternary operator so the `render` prop returns null. I suppose that for this library the render method doesn't behave as we would imagine (meaning to just render what is provided). We can either create a fork of `react-media` with these changes (I am happy to do it) or submit a PR for `react-media` but then I don't know if that would break the old behavior.

**Comment by streamich** [comment]
Consider using [`react-universal-interface`](https://github.com/streamich/react-universal-interface) to avoid such issues.
